name: Sync Feature to Staging
on:
  push:
    branches:
      - tutors_interface
      - students_interface
      - login_register

jobs:
  sync-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to Staging
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin staging
          git checkout staging
          git merge origin/${{ github.ref_name }} --no-edit
          git push origin staging