name: Feature Branch Integration
on:
  pull_request:
    branches: 
      - tutors_interface
      - students_interface
      - login_register

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Ensures pytest is available

      - name: Run Integration Tests
        run: |
          # Point to root (pwd) instead of app folder
          export PYTHONPATH=$PYTHONPATH:$(pwd) 
          pytest test/test_integration.py
        env:
          DATABASE_URL: ${{ secrets.DB_CONNECTION_DEV }}
        