name: Push to Staging
on:
  push:
    branches: [ staging ]

jobs:
  deploy-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Run All Tests
        run: |
          npm install
          npm test # Runs all tests in /test folder
        env:
          DATABASE_URL: ${{ secrets.DB_CONNECTION_STAGING }}
      - name: Merge to Main
        run: |
          git fetch origin main
          git checkout main
          git merge staging
          git push origin main
